apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

# Reference to base configuration
resources:
  - ../../base
  - mcp-secrets.sops.yaml

# Environment-specific labels
commonLabels:
  environment: staging

# Environment-specific patches
patchesStrategicMerge:
  - staging-patches.yaml

# Environment-specific images
images:
  - name: gengine-webhook-server
    newTag: latest