---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: tf-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  AWS_REGION: "us-east-1"