# This is an example SOPS-encrypted secret file
# To create this file:
# 1. Generate age key: age-keygen -o ~/flux-age-key.txt
# 2. Update .sops.yaml with your public key
# 3. Create plain secret file
# 4. Encrypt with: sops --encrypt secret.yaml > secret.sops.yaml

apiVersion: v1
kind: Secret
metadata:
    name: example-app-secrets
    namespace: staging
type: Opaque
stringData:
    # These values would be encrypted by SOPS
    api-key: your-api-key-here
    database-url: postgresql://user:password@host:5432/database
    webhook-secret: your-webhook-secret-here
    
# After SOPS encryption, this file would contain encrypted data like:
# data:
#   api-key: ENC[AES256_GCM,data:...,tag:...,type:str]
#   database-url: ENC[AES256_GCM,data:...,tag:...,type:str]
# sops:
#   kms: []
#   gcp_kms: []
#   azure_kv: []
#   hc_vault: []
#   age:
#     - recipient: age1abc123...
#       enc: -----BEGIN AGE ENCRYPTED FILE-----