---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/clusters/terraform-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system