---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: test-terraform
  namespace: tf-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./infrastructure/terraform/test
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: test-terraform-outputs