---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: webhook-server
  namespace: flux-system
spec:
  image: 549574275832.dkr.ecr.us-east-1.amazonaws.com/webhook-server
  interval: 1m
  provider: aws
  secretRef:
    name: ecr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: webhook-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: webhook-server
  filterTags:
    pattern: '^[a-f0-9]{40}-(?P<timestamp>[0-9]+)$'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: feature/clean-mcp-restructure
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
    push:
      branch: feature/clean-mcp-restructure
  update:
    path: "./infrastructure/apps"
    strategy: Setters