---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-runner
  namespace: tf-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner
  namespace: tf-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-runner
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: tf-system