name: github
description: GitHub integration for repository management, issues, PRs, and actions
category: official
version: latest
package: "@modelcontextprotocol/server-github"

execution:
  type: npx
  command: npx
  args:
    - "@modelcontextprotocol/server-github"

environment:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    required: true
    description: GitHub personal access token with appropriate permissions
    example: ghp_...
    permissions:
      - repo
      - read:org
      - workflow

# Tools will be discovered dynamically via MCP protocol

metadata:
  documentation: https://github.com/modelcontextprotocol/servers/tree/main/src/github
  repository: https://github.com/modelcontextprotocol/servers
  npm: https://www.npmjs.com/package/@modelcontextprotocol/server-github