name: github
description: GitHub integration for repository management, issues, PRs, and actions
category: official
version: latest
package: "@modelcontextprotocol/server-github"

execution:
  type: npx
  command: npx
  args:
    - "@modelcontextprotocol/server-github"

environment:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    required: true
    description: GitHub personal access token with appropriate permissions
    example: ghp_...
    permissions:
      - repo
      - read:org
      - workflow

tools:
  - create_repository
  - get_repository
  - list_repositories
  - create_issue
  - get_issue
  - list_issues
  - create_pull_request
  - get_pull_request
  - list_pull_requests
  - create_branch
  - get_file
  - search_repositories
  - push_files
  - create_or_update_file
  - create_workflow_dispatch

metadata:
  documentation: https://github.com/modelcontextprotocol/servers/tree/main/src/github
  repository: https://github.com/modelcontextprotocol/servers
  npm: https://www.npmjs.com/package/@modelcontextprotocol/server-github