name: knowledge-graph
description: Knowledge Graph Engine for code analysis, repository search, and documentation retrieval
category: native
version: 1.0.0
module: src.mcp_server.knowledge_graph_mcp

execution:
  type: python
  module: src.mcp_server.knowledge_graph_mcp
  class: KnowledgeGraphMCP

environment:
  NEO4J_URI:
    required: true
    description: Neo4j database URI
    example: bolt://localhost:7687
    default: bolt://localhost:7688
  NEO4J_USERNAME:
    required: true
    description: Neo4j username
    example: neo4j
    default: neo4j
  NEO4J_PASSWORD:
    required: true
    description: Neo4j password
    example: password123
  OPENAI_API_KEY:
    required: true
    description: OpenAI API key for embeddings
    example: sk-...

tools:
  - list_repositories
  - get_code
  - find_connections
  - search_code
  - search_docs
  - get_usage_dependencies
  - get_folder_tree

metadata:
  documentation: /home/devin/dblitz/engine/CLAUDE.md
  repository: https://github.com/dblitz/engine