name: taskmaster-ai
description: TaskMaster AI for project management, task automation, and AI-powered research
category: official
version: latest
package: task-master-ai

# How to run this MCP server
execution:
  type: npx
  command: npx
  args: 
    - task-master-ai

# Required environment variables
environment:
  OPENAI_API_KEY:
    required: true
    description: OpenAI API key for AI-powered features
    example: sk-...
  PERPLEXITY_API_KEY:
    required: false
    description: Perplexity API key for research features
    example: pplx-...

# Tools will be discovered dynamically via MCP protocol

# Additional metadata
metadata:
  documentation: https://github.com/taskmaster-ai/taskmaster
  repository: https://github.com/taskmaster-ai/taskmaster
  issues: https://github.com/taskmaster-ai/taskmaster/issues