---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webhook-server-build-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push-trigger
      interceptors:
        - ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: webhook-secret
            - name: eventTypes
              value: ["push"]
      bindings:
        - ref: webhook-server-github-binding
      template:
        ref: webhook-server-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: webhook-server-github-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: git-repo-name
      value: $(body.repository.name)
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: tekton-pipelines
type: Opaque
stringData:
  webhook-secret: "c9e63328381309a2293f948cd68fab94d81227bdeaff5fd57d0a1febdd587328"