name: Auto-Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - dev
      - 'dependabot/**'
      - 'renovate/**'
      - 'update-flux-*'
    paths-ignore:
      - 'src/gengines/**'  # Exclude submodules - handled by submodule-testing.yml

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch info
        id: branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Current branch: $BRANCH_NAME"

      - name: Check if PR already exists
        id: pr-check
        run: |
          EXISTING_PR=$(gh pr list --head "${{ steps.branch.outputs.branch_name }}" --base dev --json number --jq '.[0].number // empty')
          if [ -n "$EXISTING_PR" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$EXISTING_PR" >> $GITHUB_OUTPUT
            echo "PR #$EXISTING_PR already exists for this branch"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "No existing PR found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.pr-check.outputs.exists == 'false'
        run: |
          gh pr create \
            --title "🚀 Auto-PR: ${{ steps.branch.outputs.branch_name }}" \
            --body "## Auto-Generated Pull Request

          **Branch:** \`${{ steps.branch.outputs.branch_name }}\`
          **Target:** \`dev\` (staging environment)

          ### GitOps Workflow
          This PR was automatically created when you pushed to the feature branch.

          **Next Steps:**
          1. ✅ Flux validation will run automatically
          2. ✅ E2E tests will run automatically  
          3. ✅ Auto-merge will occur after all checks pass
          4. ✅ Changes will deploy to staging environment

          ### Branch Strategy
          - **Feature Branch** → **Dev Branch** (staging)
          - **Dev Branch** → **Main Branch** (production) 

          ---
          *This PR was automatically created by the Auto-PR workflow*" \
            --base dev \
            --head ${{ steps.branch.outputs.branch_name }} \
            --label "auto-pr,feature,staging"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on existing PR
        if: steps.pr-check.outputs.exists == 'true'
        run: |
          gh pr comment ${{ steps.pr-check.outputs.pr_number }} --body "🔄 **Auto-PR Update**: New commits pushed to \`${{ steps.branch.outputs.branch_name }}\` branch"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}