name: Flux End-to-End Testing

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  e2e-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'latest'
          
      - name: Setup Kubernetes Kind
        uses: helm/kind-action@main
        with:
          cluster_name: flux-staging-test
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
            - role: control-plane
              extraPortMappings:
              - containerPort: 80
                hostPort: 8080
                
      - name: Install Flux in Kind
        run: |
          flux install --verbose
          kubectl wait --for=condition=ready --timeout=300s -n flux-system pod --all
          
      - name: Test Flux bootstrap (staging simulation)
        run: |
          # Create a test GitRepository pointing to current branch
          cat <<EOF | kubectl apply -f -
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          metadata:
            name: test-repo
            namespace: flux-system
          spec:
            interval: 1m
            ref:
              branch: ${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
            url: https://github.com/${GITHUB_REPOSITORY}
          EOF
          
          # Create Kustomization for staging
          cat <<EOF | kubectl apply -f -
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: staging-test
            namespace: flux-system
          spec:
            interval: 1m
            path: ./infrastructure/clusters/staging
            prune: true
            sourceRef:
              kind: GitRepository
              name: test-repo
          EOF
          
      - name: Wait for reconciliation
        run: |
          # Wait for GitRepository to be ready
          kubectl wait --for=condition=ready --timeout=300s gitrepository/test-repo -n flux-system
          
          # Wait for Kustomization to be ready
          kubectl wait --for=condition=ready --timeout=300s kustomization/staging-test -n flux-system
          
      - name: Check Flux status
        run: |
          flux get all -A
          kubectl get events -n flux-system --sort-by='.lastTimestamp'
          
      - name: Verify resources created
        run: |
          # Check that namespaces are created
          kubectl get namespaces
          
          # Check that Flux components are healthy
          flux check --verbose