name: Flux End-to-End Testing

on:
  pull_request:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/flux-validation.yml'
      - '.github/workflows/flux-e2e.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/**'
      - '.github/workflows/flux-validation.yml'
      - '.github/workflows/flux-e2e.yml'

jobs:
  e2e-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'latest'
          
      - name: Setup Kubernetes Kind
        uses: helm/kind-action@main
        with:
          cluster_name: flux-staging-test
                
      - name: Install Flux in Kind
        run: |
          flux install --verbose
          kubectl wait --for=condition=ready --timeout=300s -n flux-system pod --all
          
      - name: Create test manifests
        run: |
          # Create a test directory with simple manifests
          mkdir -p ./test-e2e/base
          
          # Create a simple deployment for testing
          cat <<EOF > ./test-e2e/base/deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: flux-e2e-test
            template:
              metadata:
                labels:
                  app: flux-e2e-test
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
          EOF
          
          # Create kustomization.yaml for completeness (not used in self-contained test)
          cat <<EOF > ./test-e2e/base/kustomization.yaml
          # This file is not used in the self-contained test
          # It's here for completeness in case future tests need it
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          - deployment.yaml
          EOF
          
          # Commit test manifests
          git add ./test-e2e/
          git config --local user.email "test@example.com"
          git config --local user.name "Test User"
          git commit -m "Add e2e test manifests"
          
      - name: Test Flux functionality (self-contained)
        run: |
          # Test 1: Apply test manifests directly (no Git sync needed)
          echo "🧪 Testing direct manifest application..."
          kubectl apply -f ./test-e2e/base/deployment.yaml
          
          # Test 2: Wait for deployment to be ready
          echo "⏳ Waiting for test deployment..."
          kubectl wait --for=condition=available --timeout=120s deployment/test-deployment -n default
          
          # Test 3: Verify Flux components are healthy
          echo "🔍 Checking Flux health..."
          flux check --verbose
          
          # Test 4: Create a simple GitRepository to test Flux GitOps capability
          echo "🚀 Testing GitRepository creation..."
          cat <<EOF | kubectl apply -f -
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          metadata:
            name: flux-test-repo
            namespace: flux-system
          spec:
            interval: 5m
            ref:
              branch: main
            url: https://github.com/fluxcd/flux2-kustomize-helm-example
          EOF
          
          # Test 5: Verify GitRepository is created (don't wait for sync)
          echo "✅ Verifying GitRepository creation..."
          kubectl get gitrepository flux-test-repo -n flux-system
          
          echo "🎯 Self-contained Flux e2e test completed successfully!"
          
      - name: Final validation
        run: |
          # Final check that all components are healthy
          echo "🔍 Final Flux health check..."
          flux get all -A
          
          # Verify test deployment is still running
          echo "✅ Verifying test deployment is healthy..."
          kubectl get deployment test-deployment -n default -o wide
          
      - name: Summary
        run: |
          echo "🎉 Flux End-to-End Test Summary:"
          echo "✅ Kind cluster created successfully"
          echo "✅ Flux installed and healthy"
          echo "✅ Test manifests applied directly"
          echo "✅ Test deployment running"
          echo "✅ GitRepository creation tested"
          echo "✅ All Flux components operational"
          echo ""
          echo "🎯 Self-contained e2e test completed without Git sync dependency!"